### ISSUE TITLE
catkin_make in ROS Noetic [Error]

### ISSUE THREAD

**Issue by HappySamuel** [TixiaoShan/LIO-SAM#206]
I am trying to install the LIO-SAM in Ubuntu 20.04 and ROS Noetic. However i couldn't get it catkin_make.

Error 1:
GTSAM version: ppa gtsam (4.0.3)
Reason of using ppa GTSAM (4.0.3) is because failed to build GTSAM (4.0.2) from source. It failed at `cmake -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF ..`
![Screenshot from 2021-02-23 18-03-08](https://user-images.githubusercontent.com/18137963/108828398-c067b900-7601-11eb-838b-1243af124a85.png)
Is there any solution to this error?

Error 2:
catkin_make ERROR
![Screenshot from 2021-02-23 18-03-08](https://user-images.githubusercontent.com/18137963/108828111-66ff8a00-7601-11eb-891b-b91fc4203917.png)

What's the opencv version needed for LIO-SAM?

Best,
Samuel

**Comment by Rotoslider** [comment]
For me on Melodic with Opencv4.5 installed I had the change the line in utility.h to opencv2/opencv.hpp.

**Comment by HappySamuel** [comment]
Hi @Rotoslider 

Thanks for the info. 

@TixiaoShan 
I have successful tried out installing LIO-SAM with ROS Noetic, and we need to do the following changes:
**Step 1:** Install GTSAM 4.0.3 binary
![Screenshot from 2021-02-24 09-52-16](https://user-images.githubusercontent.com/18137963/108933897-e4211280-7686-11eb-89c5-0af0a845ffc1.png)
Reason of doing so, is because failed to install from source using the gtsam 4.0.2

**Step 2:** Configure the utility.h to use 
`#include <opencv2/opencv.hpp>` instead of `#include <opencv/cv.h>`

Step 3: Configure CMakeLists.txt to use 
`set(CMAKE_CXX_FLAGS "-std=c++14")` instead of `set(CMAKE_CXX_FLAGS "-std=c++11")`

With these 3 modifications, LIO-SAM is able to be installed on Ubuntu 20.04 and ROS Noetic. You may try it out.

Best,
Samuel

**Comment by J-Rojas** [comment]
@HappySamuel  this was very helpful. @TixiaoShan  Can this be added to the documentation?

**Comment by FrankBu0616** [comment]
@HappySamuel Thanks for the post! Supper helpful!

**Comment by juliangaal** [comment]
I created [a fork](https://github.com/juliangaal/LIO-SAM) that compiles on Ubuntu 20.04 with ROS Noetic

**Comment by willat343** [comment]
Even with @HappySamuel's changes, I still encountered a strange error:
```
error: ‘class std::unordered_map<unsigned int, std::vector<unsigned int> >’ has no member named ‘serialize’
```
which was resolved by moving `#include <opencv2/opencv.hpp>` after the `pcl` headers.

Also the stable `gtsam-release-4.0` at time of writing is now 4.0.3, so it was not necessary to install GTSAM from source.

This appears to be caused by a incompatibility between FLANN and OpenCV, whereby the `USE_UNORDERED_MAP` macro leeks from the OpenCV header and is picked by FLANN. Swapping the header order resolves this issue. See https://github.com/flann-lib/flann/issues/214 for more details.

**Comment by TixiaoShan** [comment]
Thanks for providing information for **Noetic** compiling. To summarize [HappySamuel](https://github.com/HappySamuel) and [willat343](https://github.com/willat343)'s comments:
```
1. Install GTSAM following readme
2. Configure the utility.h to use **#include <opencv2/opencv.hpp>** instead of #include <opencv/cv.h>
3. Configure CMakeLists.txt to use **set(CMAKE_CXX_FLAGS "-std=c++14")** instead of `set(CMAKE_CXX_FLAGS "-std=c++11")`
4. Move #include <opencv2/opencv.hpp> after the pcl headers
```

**Comment by leo-stan** [comment]
According to [this](https://stackoverflow.com/questions/42504592/flann-util-serialization-h-class-stdunordered-mapunsigned-int-stdvectorun) all that has to be done to fix the `flann` serialization error is to include `<pcl/kdtree/kdtree_flann.h>` before `<opencv2/opencv.hpp>`. I tested this change locally and it solved the issue.

**Comment by Abhirup0209** [comment]
There are still some compilations issues with this now and ROS Noetic. Can anyone please help me?

**Comment by X1yz** [comment]
> Hi All, I still have issues compiling in Noetic. Below is terminal feedback: ![Screenshot from 2023-03-17 11-05-59](https://user-images.githubusercontent.com/74773527/225874831-ba5a6427-53bb-473f-b37c-0946cd9fcc1a.png) Can anyone help?

i have the same problem.Have you sovled it?

**Comment by pospichal-lukas** [comment]
> > Hi All, I still have issues compiling in Noetic. Below is terminal feedback: ![Screenshot from 2023-03-17 11-05-59](https://user-images.githubusercontent.com/74773527/225874831-ba5a6427-53bb-473f-b37c-0946cd9fcc1a.png) Can anyone help?
> 
> i have the same problem.Have you sovled it?

I ran catkin make again. The build succeeded the second time. Don't ask me why.

**Comment by Kenneth-fuge** [comment]
把flann移到opencv前面
#include <pcl/kdtree/kdtree_flann.h>
// #include <opencv/cv.h>
#include <opencv2/opencv.hpp>

**Comment by TheSeanParker** [comment]
> Even with [@HappySamuel](https://github.com/HappySamuel)'s changes, I still encountered a strange error:
> 
> ```
> error: ‘class std::unordered_map<unsigned int, std::vector<unsigned int> >’ has no member named ‘serialize’
> ```
> 
> which was resolved by moving `#include <opencv2/opencv.hpp>` after the `pcl` headers.
> 
> This appears to be caused by a incompatibility between FLANN and OpenCV, whereby the `USE_UNORDERED_MAP` macro leeks from the OpenCV header and is picked by FLANN. Swapping the header order resolves this issue. See [flann-lib/flann#214](https://github.com/flann-lib/flann/issues/214) and https://stackoverflow.com/questions/42504592/flann-util-serialization-h-class-stdunordered-mapunsigned-int-stdvectorun for more details.
> 
> Also the stable `gtsam-release-4.0` at time of writing is now 4.0.3, so it was not necessary to install GTSAM from source.

In English ,you are so great;
In Chinses, you are niu people!
